[ { Address: '1135 S. 2100 East',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-05T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-05T00:00:00Z',
    Description: '**ARTIST STATEMENT**\r\n___\r\nThis collection of watercolor paintings is inspired by water. I grew up by the ocean in San Diego, California and have since traveled upstream to reside in Utah. Water in our desert climate is an intriguing conundrum. We xeriscape the front yard while the back blooms with roses and tomatoes. My personal backyard oasis is vital to my happiness.\r\n\r\nI utilized satellite imagery to create overhead abstractions of Salt Lake City neighborhoods and of the Colorado River. A birds-eye view of the city, a location with limited natural water supply, reveals a landscape lush with foliage. In contrast, one may float in the midst of the source of the culinary and irrigation supply for Las Vegas and southern California, yet a few feet from the shoreline the land reverts to desert. In contrast to these interpretive overhead views I draw the viewer to ground level by inserting specimens of magnified flora and fauna, brought in to beautify our civilization.\r\n\r\nThese paintings are highly personal, all the subjects are dear to my heart. The flowers are from photos taken at Red Butte Garden, a place where I go to find peace and where I was once employed. An overhead grid of Salt Lake City reveals the Avenues neighborhood of my first house. Floating on the Colorado River and its tributaries is a treasured pastime. And at the end of the river, one finds the sea and my childhood memories. Assembled, these paintings tell my story. All these paintings have been created within the past few years at my home in Salt Lake City.\r\n\r\nThank you to the Salt Lake City Public Library for selecting my artwork for display, they unknowingly provided the soundtrack for these paintings. When I have a free and quiet moment, rare with three boys, I push the school work and lego creations off the dining table, pull out my paints and cue up an audiobook. There is nothing like a visit to the Château d\'If or a time-travel through a tesseract before the kids come home.',
    Distance: '2.9',
    Free: 'true',
    HasTime: 'false',
    Id: '9c7811a081b54ab492a842de99baf6ba',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a5308f05-3dfa-4acd-9b39-320e4fed4be7.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Anne Penrod: Water Ways',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5609/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a5308f05-3dfa-4acd-9b39-320e4fed4be7.medium.png',
    Name: 'Anne Penrod: Water Ways',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2810079',
    Picked: 'false',
    PopularityIndex: '8',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a5308f05-3dfa-4acd-9b39-320e4fed4be7.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '402503',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10159', '3', '10103', '22' ] },
    Tickets: '',
    Venue: 'Anderson-Foothill Library',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.725439265370369',
    lm: '2016-09-21T22:20:34.389Z',
    longitude: '-111.85852557420731' },
  { Address: '455 F Street',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-05T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-05T00:00:00Z',
    Description: 'My early desire to become a museum-quality artist guides me with an unwavering faith. With all the negative, sometimes horrific events that happen in our world today, I am proud to have chosen to immerse myself in beauty and to share those experiences through my art. I am constantly setting a variety of mini goals that push me toward more artistic understanding, more growth. Through these explorations, I hope to provide tangible, visual reminders of the vast wealth of our natural world.\r\n\r\nThis show has an assortment of *plein air* (painting on location) and studio work that depicts my favorite, mountain places. In my first introduction to Alta, I felt as if I was experiencing the words in a song written by John Denver, “... coming home to a place I\'d never been before.” This was a new feeling, a new awareness to me. I listened to that feeling, trusted in it, and moved here to see where it would take me. I am so grateful that I did. Our mountains lift me up physically, emotionally, and spiritually. They truly make my heart soar.\r\n\r\nYes, you\'ll see a lot of paintings of Mount Superior. I believe that "her" beautiful face is what first triggered the artistic urge within. I love how "she" changes with the various seasons. Her beautiful winter veil can—in a moment—send snow avalanching down, piling up on the main road. As spring heats up, she sheds that white veil to reveal her butterfly. Such a lovely patch of snow. Down to her bare bones in the summer, she reigns gently, yet mightily over the multitude of wildflower carpets below. Fall finds her hunkered down in shadow as if to allow all attention to be directed at the golden aspen trees. I can never get enough of these fascinating changes.\r\n\r\nDevil\'s Castle has much the same effect upon me.\r\n\r\nFor 10 years I set my paints and hikes aside. My parents were aging and I knew that they would not always be there (except in my heart and mind). They were fun and easy to help. Now, I am back painting and experiencing this world. I hope that your experience of *High Places Make Me High* will quietly bring us a little closer together. Thanks so much for coming.',
    Distance: '4.6',
    Free: 'true',
    HasTime: 'false',
    Id: 'f0a2d992de4a4cc1a8534a12902eb0ac',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/787b7a90-bd8d-4945-a9b9-d23b0e8c3dda.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'J. Calhoun: High Places Make Me High',
          revP: '0',
          url: 'http://www.slcpl.lib.ut.us/events/view/5680/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/787b7a90-bd8d-4945-a9b9-d23b0e8c3dda.medium.png',
    Name: 'J. Calhoun: High Places Make Me High',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2702260',
    Picked: 'false',
    PopularityIndex: '5',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/787b7a90-bd8d-4945-a9b9-d23b0e8c3dda.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '402512',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '3', '10170', '5' ] },
    Tickets: '',
    Venue: 'Sweet Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.694061279296875',
    lm: '2016-09-21T22:24:44.527Z',
    longitude: '-111.87796783447266' },
  { Address: '2131 S. 1100 East',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-05T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-05T00:00:00Z',
    Description: '**ARTIST STATEMENT**\r\n___\r\nThe purpose of this show is to take a look at Salt Lake City and its beautiful environs, from its gritty winter streets to its colorful spring surprises planted between mountain and valley.\r\n\r\n**\r\n___\r\n**\r\n\r\n**ARTIST BIOGRAPHY**\r\n\r\nTerence K. Stephens recently returned to his native Salt Lake City and opened a gallery, Art270, where he showcases local artists and performers. Prior to his return, he pursued artistic endeavors in San Francisco and Seattle. He received a B.F.A. from the University of Utah in Drawing and Painting and an associates degree at Utah Technical College (now Salt Lake Community College) in Graphic Design. He also studied in Avignon, France, and in Washington, D.C.\r\n\r\nTerence served on the board of The Center On Contemporary Art (C.O.C.A.) in Seattle and his works have shown at The Seattle Asian Art Museum. He has also been commissioned for several murals in Seattle and San Francisco in homes, businesses, and government facilities.\r\n\r\nMr. Stephens\' work includes figurative painting and sculpture, landscapes, florals, and portraits (including pets). His inspirations are travel and everyday experiences. His goal is to turn people on to art. He currently is on the board of The Salt Lake Acting Company.',
    Distance: '2.8',
    Free: 'true',
    HasTime: 'false',
    Id: '83709f69e9ba46609552912d5d931391',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/30fb2dfe-f690-469d-8a4f-a89577d342cc.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Terence K. Stephens: Greater Salt Lake',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5649/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/30fb2dfe-f690-469d-8a4f-a89577d342cc.medium.png',
    Name: 'Terence K. Stephens: Greater Salt Lake',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2810295',
    Picked: 'false',
    PopularityIndex: '21',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/30fb2dfe-f690-469d-8a4f-a89577d342cc.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '402523',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10159', '3', '22' ] },
    Tickets: '',
    Venue: 'Sprague Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.725295096635818',
    lm: '2016-09-21T22:35:01.868Z',
    longitude: '-111.85957096517086' },
  { Address: '2580 Jefferson Ave',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Ogden, UT',
    Date: '2016-10-05T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-05T00:00:00Z',
    Description: 'Arts & Culture Categories: * VISUAL ARTS, * CULTURAL\r\nAudience: Children,Teens,Adults,Members\r\nType of Event: Exhibit\r\nCost: Complimentary Admission\r\nContact: ECAC staff: 801-392-6935\r\nGallery Details: The Eccles Community Art Center, a Victorian sandstone mansion, exhibits work of local, regional, and nationally known artists.  The mansion houses the offices of the art center, the Junior League, Weber Artsand Rotary.  Other buildings in the complex hold studios for the arts and dance classes sponsored by the center, which are open to the public.An excellent sales/gift gallery, which represents over sixty local Northern Utah artists, is found in the carriage house.  Colorful gardenswith a growing collection of sculpture complete the center.  Gallery/office Hours: Weekdays 9 a.m. to 5 p.m. Saturdays 9 a.m. to 3 p.m.\r\nLink: http://www.ogden4arts.org\r\nAdrian Van Suchtelen and Robin L Farr in theMain Gallery and feature the art work of Tim Dorny Peterson, Sr. and the ceramic teapots of Victoria Acoba in the Carriage House Gallery during the month of October.  A reception for the artists will be held in association with Ogden\'s Art Stroll on Friday October 7, 2016 from 5 to 8p.m.  For more information about the center and its exhibits, please visit: www.ogden4arts.org.',
    Distance: '31.9',
    Free: 'true',
    HasTime: 'false',
    Id: '2166d7dc63ac46f5911a91d2339aa855',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/0281b96a-8483-4653-bda6-090ac7d14fd0.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Adrian Van Suctelen & Robin Farr',
          revP: '0',
          url: 'http://www.ogden4arts.org/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/0281b96a-8483-4653-bda6-090ac7d14fd0.medium.png',
    Name: 'Adrian Van Suctelen & Robin Farr',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2756226',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/0281b96a-8483-4653-bda6-090ac7d14fd0.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '409067',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '3', '10170', '5' ] },
    Tickets: '',
    Venue: 'Eccles Community Art Center',
    Zip: '84401',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '41.2188606262207',
    lm: '2016-09-28T19:08:55.069Z',
    longitude: '-111.96415710449219' },
  { Address: '1340 E. 100 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:00:00Z',
    DateStart: '2016-10-06T08:00:00Z',
    Description: 'In *Wait Here *Please, mixed media artist Lexi Rae Johnson uses multiple paintings and an installation of a mythological city called *Warm Land *to create an environment in which viewers can step into a portal of otherworldliness. Johnson says of her work, “Here, dogs will fight for you. Here, absurd corridors will unfold for you. Please allow me to introduce to impossible combinations.” Through her work, Johnson creates a space where viewers can forget their surroundings and become one with her created landscape.\r\n\r\n___\r\n\r\nJohnson will present a gallery talk on Friday, October 21 from 5:30-6:00 p.m.',
    Distance: '1.9',
    Free: 'true',
    HasTime: 'true',
    Id: '513ec6be95d14634b1d363add3864d78',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: '"Wait Here Please": Lexi Rae Johnson',
          revP: '0',
          url: 'http://www.saltlakearts.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.medium.png',
    Name: '"Wait Here Please": Lexi Rae Johnson',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2836655',
    Picked: 'false',
    PopularityIndex: '8',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '409816',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10256', '3' ] },
    Tickets: '',
    Venue: 'Art Barn/Finch Lane Gallery',
    Zip: '84101',
    ct: 
     { email: 'kandace.steadman@slcgov.com',
       name: 'Kandace Steadman',
       org: 'Salt Lake City Arts Council',
       phone: '801 596-5000' },
    enhance: 'false',
    latitude: '40.767067819833755',
    lm: '2016-09-29T23:16:56.016Z',
    longitude: '-111.85252815485' },
  { Address: '201 Presidents Cir',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'Registration for creative dance, satellite, ballet, hip hop, and Dancers with Disabilities classes for the the 2016-2017 school year is now available.It should be an amazing year of dance.',
    Distance: '2',
    Free: 'false',
    HasTime: 'true',
    Id: 'ce17a9bf595f48c18d2367a30ef5a2c2',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.medium.png',
    Name: 'Tanner Dance Classes',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2628342',
    Picked: 'false',
    PopularityIndex: '8',
    Price: '100',
    PriceHigh: '750',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '2', '17', '18' ] },
    Tickets: 
     { jsLink: 
        { name: 'Tanner Dance Classes',
          revP: '0',
          url: 'http://www.tannerdance.utah.edu/' } },
    Venue: 'The University of Utah',
    Zip: '84112',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7655087858',
    lm: '2016-07-31T17:09:19.314Z',
    longitude: '-111.8498969078' },
  { Address: '1355 W 3100 S',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'West Valley City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'Exquisite objects, made for everyday use according to inherited styles of beadwork, weaving, pottery and homestead painting, reveal an astonishing integrity of design and innovation with contemporary materials and forms.  And yet, the iconic master artists of rural southern Africa, national treasures, share great concern that their skill might not survive beyond their own generation. \r\n\r\nAfrica meets Africa brings these artists’ knowledge into the classroom with unique arts-skills learning methodology, integrating visual arts, history and mathematics. For example, students do geometry with their hands, as they make beadwork and weave according to inherited southern African styles. In this exhibition cultural expression is contextualized in relation to past and present needs.',
    Distance: '4.4',
    Free: 'true',
    HasTime: 'true',
    Id: 'ed30f092ddde4331aa38cf1d863f860d',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Eye Hand Mind: Selections from the Africa Meets Africa Project',
          revP: '0',
          url: 'http://www.culturalcelebration.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.medium.png',
    Name: 'Eye Hand Mind: Selections from the Africa Meets Africa Project',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2723665',
    Picked: 'false',
    PopularityIndex: '10',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: '3' },
    Tickets: '',
    Venue: 'Utah Cultural Celebration Center',
    Zip: { '$': { 'i:nil': 'true' } },
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7037773132',
    lm: '2016-08-25T21:26:59.804Z',
    longitude: '-111.9288253784' },
  { Address: '401 East 200 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'The First Annual Zion Art Exhibition is an opportunity to view the winning works of our first competition, showcasing LDS artists in conjunction General Conference in downtown SLC. Come and meet the artists, learn about their works, and help us spread the word of the amazing talents of the more than 10,000 LDS artists working today.',
    Distance: '0.2',
    Free: 'true',
    HasTime: 'true',
    Id: 'ffa7eded37574f568f9c452a1d41fd66',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Zion Art Exhibition',
          revP: '0',
          url: 'http://zionartsociety.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.medium.png',
    Name: 'Zion Art Exhibition',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2762927',
    Picked: 'false',
    PopularityIndex: '6',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '389641',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10159', '23', '3', '22' ] },
    Tickets: '',
    Venue: 'Anthony\'s Fine Art',
    Zip: '84101',
    ct: 
     { email: 'contact@zionartsociety.org',
       name: 'Eric Biggart',
       org: 'Zion Art Society',
       phone: '801-369-8894' },
    enhance: 'false',
    latitude: '40.760442763566971',
    lm: '2016-09-08T14:13:25.467Z',
    longitude: '-111.88530005514622' },
  { Address: '201 S. 1460 East',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T14:00:00Z',
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'The University of Utah will host its 9th annual campus Farmers Market during the fall semester of 2016. The market links local growers and artisans with the campus community and provides access to fresh, healthy, local produce and unique arts and crafts. Follow us on Facebook for regular updates!',
    Distance: '2.1',
    Free: 'true',
    HasTime: 'true',
    Id: 'd612f2bb2afa4a8da7c76435f8fda0e0',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FarmersMarket' },
    Links: 
     { jsLink: 
        { name: 'U of U Farmers Market',
          revP: '0',
          url: 'https://www.facebook.com/UofUFarmersMarket' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.medium.png',
    Name: 'U of U Farmers Market',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2357106',
    Picked: 'false',
    PopularityIndex: '9',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '296492',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '385', '54', '76' ] },
    Tickets: '',
    Venue: 'University of Utah Tanner Plaza',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.766249746084213',
    lm: '2016-05-16T18:06:05.824Z',
    longitude: '-111.84856921434402' },
  { Address: '58 North State Street',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Orem, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'Laptime: Parents, infants, and toddlers are invited to join us in the Ship\'s Cove every Tuesday, Wednesday, and Thursday at 10 am for a 20 minute program of songs, stories, and entertainment. \r\n\r\n___\r\n\r\nStorytime: Tuesday, Wednesday, and Thursday at 10:30 am in the Storytelling Wing. A 30 minute program for preschoolers & young school age children with stories, puppets & activities to engage youngsters & highlight the joys of books & storytelling.',
    Distance: '33.6',
    Free: 'true',
    HasTime: 'true',
    Id: 'ae2ca23b9ccc4a2396ae98833f4ed0c7',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Laptime/Storytime',
          revP: '0',
          url: 'http://oremlibrary.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.medium.png',
    Name: 'Laptime/Storytime',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '679608',
    Picked: 'false',
    PopularityIndex: '6',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '4', '29', '425', '10', '65', '15', '80' ] },
    Tickets: '',
    Venue: 'Orem Public Library',
    Zip: { '$': { 'i:nil': 'true' } },
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.2969',
    lm: '2016-07-02T19:56:07.674Z',
    longitude: '-111.69465' },
  { Address: '1575 W. 1000 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'Take part in a crochet, knitting, or other craft project every Tuesday and Thursday. All are invited to bring their own supplies or use provided crochet hooks, Knifty Knitters, knitting needles, and yarn.',
    Distance: '3.3',
    Free: 'true',
    HasTime: 'true',
    Id: 'b6d4d36d5f35474a992ab313960d9429',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'Yarn Social',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5402/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.medium.png',
    Name: 'Yarn Social',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2771870',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '391661',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '51', '278', '10028', '76', '10026' ] },
    Tickets: '',
    Venue: 'Salt Lake City Library Day-Riverside Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.790485',
    lm: '2016-09-12T15:46:10.916Z',
    longitude: '-111.936347' },
  { Address: '1000 S. 900 West',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T14:00:00Z',
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'The atmosphere at the People\'s Market is friendly and inviting. Visit with our local artisans, enjoy fresh prepared food, purchase some of the best produce to be found locally, and enjoy the live performances by local musicians.\r\n\r\nWe have different Special Events through out the Season, including Book Day where you can swap books with others at the Market, and Pet Day when we promote the many rescue organizations who bring out wonderful animals who are in need of good homes. We also promote the talented youth of the community to come: to learn arts and crafts, sell items that they have made themselves, or even perform musically during open mic sessions at the Market.',
    Distance: '1.7',
    Free: 'true',
    HasTime: 'true',
    Id: 'a456d3185e454892a59d5c71efc47618',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FarmersMarket' },
    Links: 
     { jsLink: 
        { name: '9th West Farmers Market',
          revP: '0',
          url: 'http://9thwestfarmersmarket.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.medium.png',
    Name: '9th West Farmers Market',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2845797',
    Picked: 'false',
    PopularityIndex: '9',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '411155',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '385', '74', '42', '8', '12', '54', '76' ] },
    Tickets: '',
    Venue: 'The People\'s Market',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.748195648193359',
    lm: '2016-09-30T17:33:17.7Z',
    longitude: '-111.91752624511719' },
  { Address: '4883 S State St',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Murray, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T23:30:00Z',
    DateStart: '2016-10-06T11:00:00Z',
    Description: '$2.50 Domestic Drafts every Thursday.  Pair that with $2 sliders and Thursday Night Football and youve got a party.  Check out our website and Facebook Page for the weekly Specialty Slider of the Day only $3',
    Distance: '6.6',
    Free: 'true',
    HasTime: 'true',
    Id: 'f5d6d6e1c60445879b386b6d5170c0cb',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Thirsty Thursdays',
          revP: '0',
          url: 'http://www.Facebook.com/Kick N It Sports Bar' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.medium.png',
    Name: 'Thirsty Thursdays',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2724741',
    Picked: 'false',
    PopularityIndex: '7',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '377095',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '12', '14', '10252', '75' ] },
    Tickets: '',
    Venue: 'Kick N It Sports Bar',
    Zip: '84107',
    ct: 
     { email: 'kicknitatjuices@gmail.com',
       name: 'Justin Troyer',
       org: 'Kick N It Sports Grill',
       phone: '801-448-6230' },
    enhance: 'false',
    latitude: '40.665349066257477',
    lm: '2016-08-25T21:27:17.927Z',
    longitude: '-111.88825115561485' },
  { Address: '175 E. 200 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T11:00:00Z',
    Description: 'CUAC is pleased to present Discover Zaqistan: The Art of Adventure by the Zaqistan Tourism Board. The Republic of Zaqistan is located just west of the Great Salt Lake. Founded in 2005 by New York City-based artist Zaq Landsberg as a response to the political climate at the time, the project continues to be conceptually tied to current events. This year, Zaqistan is opening up its doors to tourism and partnering with *CUAC* to host expeditions into the desolate nation as well as an exhibition on the country.',
    Distance: '0.4',
    Free: 'true',
    HasTime: 'true',
    Id: '961704d0e11b466388a2c46e882f3bb7',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Discover Zaqistan: The Art of Adventure',
          revP: '0',
          url: 'http://cuartcenter.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.medium.png',
    Name: 'Discover Zaqistan: The Art of Adventure',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2759785',
    Picked: 'false',
    PopularityIndex: '11',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '388158',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '32', '3', '5' ] },
    Tickets: '',
    Venue: 'CUAC',
    Zip: '84101',
    ct: 
     { email: 'art@cuartcenter.org',
       name: 'Nancy Rivera',
       org: 'CUAC',
       phone: '385-215-6768' },
    enhance: 'false',
    latitude: '40.7657470703125',
    lm: '2016-09-07T16:03:56.227Z',
    longitude: '-111.88483428955078' },
  { Address: '202 W. 300 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T12:00:00Z',
    Description: 'The annual Utah Humanities Book Festival is Utah’s oldest and only statewide book festival and has become Utah’s signature literary event.\r\n\r\nEach year, the festival is a chance for book lovers of all types to enjoy some great, free-of-charge literary events at locations throughout Utah.\r\n\r\nMany thanks to the Book Festival’s sponsors: the George S and Dolores Dore Eccles Foundation, the R. Harold Burton Foundation, Chevron, the Salt Lake City Public Library, Salt Lake County Zoo, Arts & Parks Fund, the Utah Office of Tourism, the National Endowment for the Humanities, the Charles Redd Center for Western Studies, The King’s English Bookshop, Weller Book Works, *Catalyst*, *SLUG Magazine*, *The Enterprise*, and *City Weekly*.',
    Distance: '1.1',
    Free: 'true',
    HasTime: 'true',
    Id: '54cabadd6a8b45e8b7e6dc54001eb438',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FestivalFair' },
    Links: 
     { jsLink: 
        { name: 'Utah Humanities Book Festival',
          revP: '0',
          url: 'http://www.utahhumanities.org/index.php/Center-for-the-Book/book-festival.html' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.medium.png',
    Name: 'Utah Humanities Book Festival',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2816927',
    Picked: 'false',
    PopularityIndex: '17',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '407751',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '31', '453', '189', '4', '5' ] },
    Tickets: '',
    Venue: 'Utah Humanities',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.773826315999031',
    lm: '2016-09-28T04:52:43.856Z',
    longitude: '-111.89963042736053' },
  { Address: '280 W. 500 N.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T16:00:00Z',
    Description: 'Receive one-on-one collaborative writing assistance and helpful feedback in a supportive environment. Bring any type of writing: resumes, essays, short stories, or letters. Writing Coaching is open to all ages.\r\n\r\nIt\'s free, though schedule 30-minute session or submit work at the Community Writing Center\'s website, http://www.slcc.edu/cwc.',
    Distance: '1.4',
    Free: 'true',
    HasTime: 'true',
    Id: '542af89750b04d49a0d8ea357825859e',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'SLCC Community Writing Center Writing Coaching',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5831/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.medium.png',
    Name: 'SLCC Community Writing Center Writing Coaching',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785003',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '395623',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '27', '7', '4' ] },
    Tickets: '',
    Venue: 'Marmalade Library',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.775393396615982',
    lm: '2016-09-15T14:08:09.196Z',
    longitude: '-111.90541863441467' },
  { Address: '577 S. 900 West',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:00:00Z',
    DateStart: '2016-10-06T16:00:00Z',
    Description: 'My paintings come from my heart. It would be easy for me to edit out all that is meaningful in my paintings by judging an inspiration as too sentimental, too complicated, or just plain crazy. Wrestling with my inner voices, both angels and demons, I struggle to create a personal visual language.\r\n\r\nPainting affirms my love of the messy tactile world, the world of color and surfaces. The paint becomes my micro-universe where I play with textures, rhythms of line and patterns of form, and, more importantly, the duality of creation and destruction. I layer the paint and collage to create real depth on the pictorial surface. Primitive art inspires my work in its disregard for anatomical correctness and illusionary effects of perspective. An Egyptian frontal view of the shoulders, an Aboriginal dot, an Assyrian eye facing forward in a facial profile, and an Anasazi headdress can all be found in my work. Much inspiration comes from the work of Paul Klee, Picasso, and Chagall who were each inspired, like me, by primitive art.\r\n\r\nThe subjects of my work sometimes reflects experiences my life with my family and animals, but they can also be a reflection of the inner journeys of my mind. This messy humanness I share with all the people who have come before me and who will come after me fuels my artistic engine. Through deceptively simple images and rich layering of texture, I intend for my paintings to speak beyond culture, time, and location. Employing a personal symbolic language, my paintings are the vehicle in my search for wholeness and connection.',
    Distance: '1.2',
    Free: 'true',
    HasTime: 'true',
    Id: '3139bc3ca2484ceaa735d8392d68ddc1',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Willamarie Huelskamp: A Peaceful Place',
          revP: '0',
          url: 'http://www.slcpl.lib.ut.us/events/view/5615/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.medium.png',
    Name: 'Willamarie Huelskamp: A Peaceful Place',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2615308',
    Picked: 'false',
    PopularityIndex: '8',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '402507',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '3', '10170', '5' ] },
    Tickets: '',
    Venue: 'Salt Lake City Chapman Library',
    Zip: '84101',
    ct: 
     { email: { '$': { 'i:nil': 'true' } },
       name: { '$': { 'i:nil': 'true' } },
       org: { '$': { 'i:nil': 'true' } },
       phone: '(801) 594-8623, (801) 524-8200' },
    enhance: 'false',
    latitude: '40.749713256955147',
    lm: '2016-09-21T22:22:42.295Z',
    longitude: '-111.90740682184696' },
  { Address: '1575 W. 1000 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:30:00Z',
    DateStart: '2016-10-06T16:30:00Z',
    Description: 'Hang out with other neighborhood teens in a space created for you! The Teen Zone is a space made just for teens ages 12–18 that is open every Monday, Thursday, and Friday. Teens can participate in a designated activity that the Teen Zone is hosting, or can use the space to hang out, chat with friends, lounge on some comfy chairs, noodle on a ukulele, or curl up with a book.',
    Distance: '3.3',
    Free: 'true',
    HasTime: 'true',
    Id: '3cdf07146b0643aa85c18accda599a88',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'Teen Zone',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5689/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.medium.png',
    Name: 'Teen Zone',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785200',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '395686',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '81', '10255', '358', '35', '5', '15', '53', '76' ] },
    Tickets: '',
    Venue: 'Day-Riverside Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.790485382080078',
    lm: '2016-09-15T14:08:15.553Z',
    longitude: '-111.93634796142578' },
  { Address: '1375 S. Concord St.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T16:30:00Z',
    Description: 'Flex your creativity and learn a variety of new crafts. Each week, teens can take part in creative workshops with supplies provided by the Library. *No registration is required.*',
    Distance: '2.5',
    Free: 'true',
    HasTime: 'true',
    Id: '61014bb3cb504c4d8d1fc57f2cde20e9',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.medium.png',
    Name: 'Teen DIY',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2771880',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '391680',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '51', '81', '10255', '35', '5', '15', '76' ] },
    Tickets: '',
    Venue: 'Salt Lake City Glendale Library',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.738994598388672',
    lm: '2016-09-19T23:11:23.333Z',
    longitude: '-111.92671966552734' },
  { Address: '2750 N. University Park Blvd.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Layton, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T17:30:00Z',
    Description: '18th Annual WSU Diversity Conference\r\n\r\n“Privileged History: Where Did All the Diversity Go?” with Dr\\. James W\\. Loewen, author of “Lies My Teacher Told Me”\r\n\r\nOpening Session at WSU Davis:\r\n"Precious Knowledge" Film and Discussion\r\nOctober 6, 2016\r\n5:30 \\- 8 p\\.m\\.\r\nBuilding 3 Ballrooms',
    Distance: '21.5',
    Free: 'true',
    HasTime: 'true',
    Id: 'e973df57f52b43f4b51919441b52583a',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: '18th Annual WSU Diversity Conference',
          revP: '0',
          url: 'http://www.weber.edu/diversity/wsu-diversity-conference.html' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.medium.png',
    Name: '18th Annual WSU Diversity Conference',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2767379',
    Picked: 'false',
    PopularityIndex: '6',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '7', '39' ] },
    Tickets: '',
    Venue: 'Weber State University Davis Campus',
    Zip: '84041',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '41.0659294128418',
    lm: '2016-09-09T00:36:18.455Z',
    longitude: '-111.96102142333984' },
  { Address: '450 W. Center St.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Provo, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T19:00:00Z',
    DateStart: '2016-10-06T17:30:00Z',
    Description: 'Come hear local author David Pace read from his debut novel, *Dream House on Golan Drive!*\r\n\r\nIt is the year 1972, and Riley Hartley finds that he, his family, community, and his faith are entirely indistinguishable from each other. He is eleven. A young woman named Lucy claims God has revealed to her that she is to live with Riley’s family. Her quirks are strangely disarming, her relentless questioning of their lives incendiary and sometimes comical. Her way of taking religious practice to its logical conclusion leaves a strong impact on her hosts and propels Riley outside his observable universe and toward a trajectory of self-discovery.\r\n\r\n___\r\n Set in Provo and New York City during the seventies and eighties, the story encapsulates the normal expectations of a Mormon experience and turns them on their head. The style, too, is innovative in how it employs “Zed,” one of the apocryphal Three Nephites who with another immortal figure, the Wandering Jew of post-biblical legend, engage regularly in light-hearted banter and running commentary, animating the story and leavening the heartache with humor and tenderness.',
    Distance: '38.2',
    Free: 'true',
    HasTime: 'true',
    Id: '9ca9ec7890034cdb9d34f87f71da9076',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'Author' },
    Links: 
     { jsLink: 
        { name: 'David Pace: Dream House on Golan Drive',
          revP: '0',
          url: 'http://pioneerbook.com/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.medium.png',
    Name: 'David Pace: Dream House on Golan Drive',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2808563',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '401680',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '4', '189' ] },
    Tickets: '',
    Venue: 'Pioneer Book',
    Zip: '84606',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.234066009521484',
    lm: '2016-09-21T18:20:55.32Z',
    longitude: '-111.66659545898437' },
  { Address: '2131 S 1100 E',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T19:00:00Z',
    DateStart: '2016-10-06T17:30:00Z',
    Description: 'Join us for a U Drive Electric Workshop on Thursday, October 6th at the Sprague Library Meeting Room. The U Drive Electric Team will be on hand to tell you more about the benefits of driving electric, and how U Drive Electric can help you make the switch to an EV. The participating dealerships will also have EVs on display before and after the workshop. Presentations to be followed by Q&A. Please RSVP.',
    Distance: '2.8',
    Free: 'true',
    HasTime: 'true',
    Id: 'f8430792bce343aa820b028ae894d7e3',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'U Drive Electric Workshop',
          revP: '0',
          url: 'http://utahev.org/events/3-u-drive-electric-workshop-sprague-library-meeting-room' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.medium.png',
    Name: 'U Drive Electric Workshop',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2840068',
    Picked: 'false',
    PopularityIndex: '5',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '410074',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '39', '10120', '7', '11' ] },
    Tickets: 
     { jsLink: 
        { name: 'U Drive Electric Workshop',
          revP: '0',
          url: 'http://utahev.org/events/3-u-drive-electric-workshop-sprague-library-meeting-room' } },
    Venue: 'Sprague Library Meeting Room',
    Zip: '84101',
    ct: 
     { email: 'liamharry0506@gmail.com',
       name: 'Liam Harry',
       org: 'Utah Clean Energy',
       phone: { '$': { 'i:nil': 'true' } } },
    enhance: 'false',
    latitude: '40.725295096635818',
    lm: '2016-09-29T23:17:21.308Z',
    longitude: '-111.85957096517086' },
  { Address: '210 E. 400 S.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T20:00:00Z',
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Social media (like Facebook and Twitter, to name a couple) is one of the most common means to spread ideas and information in our world. While social media offers great tools for exchanging ideas and opinions, it can also create conflict and problems. In this workshop, you will learn how to best structure your social media posts to engage and persuade in a positive and productive way. Bring an internet capable device or use one of ours so we can create posts during the workshop.\r\n\r\n**Cost: Free. No registration is required.**',
    Distance: '0.2',
    Free: 'true',
    HasTime: 'true',
    Id: '9638a939aaa04ca3b80f31785d7f120c',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Writing for Change: Social Media',
          revP: '0',
          url: 'http://www.slcc.edu/cwc/index.aspx' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.medium.png',
    Name: 'Writing for Change: Social Media',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785984',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: 'Free',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '396082',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '27', '39', '41', '4', '7' ] },
    Tickets: '',
    Venue: 'Salt Lake Community College Community Writing Center',
    Zip: '84101',
    ct: 
     { email: 'cwc@slcc.edu',
       name: 'Nic Contreras',
       org: 'SLCC Community Writing Center',
       phone: '(801)674-2036' },
    enhance: 'false',
    latitude: '40.759559631347656',
    lm: '2016-09-15T04:38:34.696Z',
    longitude: '-111.88392639160156' },
  { Address: '536 W. 100 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Metalcore band Beartooth is bringing their tour in support of their latest album, *Aggressive*, to The Complex October 6th. Come rock out!',
    Distance: '1.1',
    Free: 'false',
    HasTime: 'true',
    Id: '1ba837e3d9ce417dbfdaafd577818be0',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.medium.png',
    Name: 'Beartooth',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2589630',
    Picked: 'false',
    PopularityIndex: '8',
    Price: '19.50',
    PriceHigh: '25',
    PriceText: '$19.50 Adv/$25 Day Of',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '404240',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '17', '2' ] },
    Tickets: 
     { jsLink: 
        { name: 'Beartooth',
          revP: '0',
          url: 'http://smithstix.com/music/event/18926/beartooth-oct-6' } },
    Venue: 'The Complex',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.767715454101563',
    lm: '2016-09-23T17:39:23.387Z',
    longitude: '-111.90690612792969' },
  { Address: '49 S Main St',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Spanish Fork, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Come join Austin Brunson, Family Life Educator, from USU to learn how to follow your heart without losing your mind\\. You can sign up for classes at www\\.eventbrite\\.com, or at healthyrelationshipsutah\\.org\\.',
    Distance: '46.6',
    Free: 'true',
    HasTime: 'true',
    Id: '371c1aba5d1240a78618b16767f05581',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'ServeDaily',
          revP: '0',
          url: 'http://Join Family Life Educator Austin Brunson for healthy relationship tips' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.medium.png',
    Name: 'Are You Over 18 and are Single or Dating?',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2814292',
    Picked: 'false',
    PopularityIndex: '12',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10', '64', '7', '41' ] },
    Tickets: '',
    Venue: 'Spanish Fork Library',
    Zip: '84660',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.1091615111',
    lm: '2016-09-26T13:51:06.99Z',
    longitude: '-111.6547306627' } ]