[ { Address: '1340 E. 100 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:00:00Z',
    DateStart: '2016-10-06T08:00:00Z',
    Description: 'In *Wait Here *Please, mixed media artist Lexi Rae Johnson uses multiple paintings and an installation of a mythological city called *Warm Land *to create an environment in which viewers can step into a portal of otherworldliness. Johnson says of her work, “Here, dogs will fight for you. Here, absurd corridors will unfold for you. Please allow me to introduce to impossible combinations.” Through her work, Johnson creates a space where viewers can forget their surroundings and become one with her created landscape.\r\n\r\n___\r\n\r\nJohnson will present a gallery talk on Friday, October 21 from 5:30-6:00 p.m.',
    Distance: '1.9',
    Free: 'true',
    HasTime: 'true',
    Id: '513ec6be95d14634b1d363add3864d78',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: '"Wait Here Please": Lexi Rae Johnson',
          revP: '0',
          url: 'http://www.saltlakearts.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.medium.png',
    Name: '"Wait Here Please": Lexi Rae Johnson',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2836655',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/8743adf5-682d-4cc3-a8cd-9874ec12691d.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '409816',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10256', '3' ] },
    Tickets: '',
    Venue: 'Art Barn/Finch Lane Gallery',
    Zip: '84101',
    ct: 
     { email: 'kandace.steadman@slcgov.com',
       name: 'Kandace Steadman',
       org: 'Salt Lake City Arts Council',
       phone: '801 596-5000' },
    enhance: 'false',
    latitude: '40.767067819833755',
    lm: '2016-09-29T23:16:56.016Z',
    longitude: '-111.85252815485' },
  { Address: '201 Presidents Cir',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'Registration for creative dance, satellite, ballet, hip hop, and Dancers with Disabilities classes for the the 2016-2017 school year is now available.It should be an amazing year of dance.',
    Distance: '2',
    Free: 'false',
    HasTime: 'true',
    Id: 'ce17a9bf595f48c18d2367a30ef5a2c2',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.medium.png',
    Name: 'Tanner Dance Classes',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2628342',
    Picked: 'false',
    PopularityIndex: '8',
    Price: '100',
    PriceHigh: '750',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '2', '17', '18' ] },
    Tickets: 
     { jsLink: 
        { name: 'Tanner Dance Classes',
          revP: '0',
          url: 'http://www.tannerdance.utah.edu/' } },
    Venue: 'The University of Utah',
    Zip: '84112',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7655087858',
    lm: '2016-07-31T17:09:19.314Z',
    longitude: '-111.8498969078' },
  { Address: '1355 W 3100 S',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'West Valley City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'Exquisite objects, made for everyday use according to inherited styles of beadwork, weaving, pottery and homestead painting, reveal an astonishing integrity of design and innovation with contemporary materials and forms.  And yet, the iconic master artists of rural southern Africa, national treasures, share great concern that their skill might not survive beyond their own generation. \r\n\r\nAfrica meets Africa brings these artists’ knowledge into the classroom with unique arts-skills learning methodology, integrating visual arts, history and mathematics. For example, students do geometry with their hands, as they make beadwork and weave according to inherited southern African styles. In this exhibition cultural expression is contextualized in relation to past and present needs.',
    Distance: '4.4',
    Free: 'true',
    HasTime: 'true',
    Id: 'ed30f092ddde4331aa38cf1d863f860d',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Eye Hand Mind: Selections from the Africa Meets Africa Project',
          revP: '0',
          url: 'http://www.culturalcelebration.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.medium.png',
    Name: 'Eye Hand Mind: Selections from the Africa Meets Africa Project',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2723665',
    Picked: 'false',
    PopularityIndex: '7',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/133ba2eb-0b1e-4119-a960-7ddbc166ab8f.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: '3' },
    Tickets: '',
    Venue: 'Utah Cultural Celebration Center',
    Zip: { '$': { 'i:nil': 'true' } },
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7037773132',
    lm: '2016-08-25T21:26:59.804Z',
    longitude: '-111.9288253784' },
  { Address: '401 East 200 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T09:00:00Z',
    Description: 'The First Annual Zion Art Exhibition is an opportunity to view the winning works of our first competition, showcasing LDS artists in conjunction General Conference in downtown SLC. Come and meet the artists, learn about their works, and help us spread the word of the amazing talents of the more than 10,000 LDS artists working today.',
    Distance: '0.2',
    Free: 'true',
    HasTime: 'true',
    Id: 'ffa7eded37574f568f9c452a1d41fd66',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Zion Art Exhibition',
          revP: '0',
          url: 'http://zionartsociety.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.medium.png',
    Name: 'Zion Art Exhibition',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2762927',
    Picked: 'false',
    PopularityIndex: '6',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/babbc3bd-594b-4bc9-b868-5bf7cf0388ce.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '389641',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10159', '23', '3', '22' ] },
    Tickets: '',
    Venue: 'Anthony\'s Fine Art',
    Zip: '84101',
    ct: 
     { email: 'contact@zionartsociety.org',
       name: 'Eric Biggart',
       org: 'Zion Art Society',
       phone: '801-369-8894' },
    enhance: 'false',
    latitude: '40.760442763566971',
    lm: '2016-09-08T14:13:25.467Z',
    longitude: '-111.88530005514622' },
  { Address: '201 S. 1460 East',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T14:00:00Z',
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'The University of Utah will host its 9th annual campus Farmers Market during the fall semester of 2016. The market links local growers and artisans with the campus community and provides access to fresh, healthy, local produce and unique arts and crafts. Follow us on Facebook for regular updates!',
    Distance: '2.1',
    Free: 'true',
    HasTime: 'true',
    Id: 'd612f2bb2afa4a8da7c76435f8fda0e0',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FarmersMarket' },
    Links: 
     { jsLink: 
        { name: 'U of U Farmers Market',
          revP: '0',
          url: 'https://www.facebook.com/UofUFarmersMarket' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.medium.png',
    Name: 'U of U Farmers Market',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2357106',
    Picked: 'false',
    PopularityIndex: '7',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/def826d7-306f-41a9-9463-f4003054c21a.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '296492',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '385', '54', '76' ] },
    Tickets: '',
    Venue: 'University of Utah Tanner Plaza',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.766249746084213',
    lm: '2016-05-16T18:06:05.824Z',
    longitude: '-111.84856921434402' },
  { Address: '58 North State Street',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Orem, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'Laptime: Parents, infants, and toddlers are invited to join us in the Ship\'s Cove every Tuesday, Wednesday, and Thursday at 10 am for a 20 minute program of songs, stories, and entertainment. \r\n\r\n___\r\n\r\nStorytime: Tuesday, Wednesday, and Thursday at 10:30 am in the Storytelling Wing. A 30 minute program for preschoolers & young school age children with stories, puppets & activities to engage youngsters & highlight the joys of books & storytelling.',
    Distance: '33.6',
    Free: 'true',
    HasTime: 'true',
    Id: 'ae2ca23b9ccc4a2396ae98833f4ed0c7',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Laptime/Storytime',
          revP: '0',
          url: 'http://oremlibrary.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.medium.png',
    Name: 'Laptime/Storytime',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '679608',
    Picked: 'false',
    PopularityIndex: '10',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/555a730a-74b6-43ad-9552-5c71d239a736.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '4', '29', '425', '10', '65', '15', '80' ] },
    Tickets: '',
    Venue: 'Orem Public Library',
    Zip: { '$': { 'i:nil': 'true' } },
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.2969',
    lm: '2016-07-02T19:56:07.674Z',
    longitude: '-111.69465' },
  { Address: '1575 W. 1000 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'Take part in a crochet, knitting, or other craft project every Tuesday and Thursday. All are invited to bring their own supplies or use provided crochet hooks, Knifty Knitters, knitting needles, and yarn.',
    Distance: '3.3',
    Free: 'true',
    HasTime: 'true',
    Id: 'b6d4d36d5f35474a992ab313960d9429',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'Yarn Social',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5402/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.medium.png',
    Name: 'Yarn Social',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2771870',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/f21d35ca-f489-4f2c-8eff-da2aba8ee711.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '391661',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '51', '278', '10028', '76', '10026' ] },
    Tickets: '',
    Venue: 'Salt Lake City Library Day-Riverside Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.790485',
    lm: '2016-09-12T15:46:10.916Z',
    longitude: '-111.936347' },
  { Address: '1000 S. 900 West',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T14:00:00Z',
    DateStart: '2016-10-06T10:00:00Z',
    Description: 'The atmosphere at the People\'s Market is friendly and inviting. Visit with our local artisans, enjoy fresh prepared food, purchase some of the best produce to be found locally, and enjoy the live performances by local musicians.\r\n\r\nWe have different Special Events through out the Season, including Book Day where you can swap books with others at the Market, and Pet Day when we promote the many rescue organizations who bring out wonderful animals who are in need of good homes. We also promote the talented youth of the community to come: to learn arts and crafts, sell items that they have made themselves, or even perform musically during open mic sessions at the Market.',
    Distance: '1.7',
    Free: 'true',
    HasTime: 'true',
    Id: 'a456d3185e454892a59d5c71efc47618',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FarmersMarket' },
    Links: 
     { jsLink: 
        { name: '9th West Farmers Market',
          revP: '0',
          url: 'http://9thwestfarmersmarket.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.medium.png',
    Name: '9th West Farmers Market',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2845797',
    Picked: 'false',
    PopularityIndex: '8',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/6ea01022-34cb-402b-92c8-74d72ec1e272.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '411155',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '385', '74', '42', '8', '12', '54', '76' ] },
    Tickets: '',
    Venue: 'The People\'s Market',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.748195648193359',
    lm: '2016-09-30T17:33:17.7Z',
    longitude: '-111.91752624511719' },
  { Address: '4883 S State St',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Murray, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T23:30:00Z',
    DateStart: '2016-10-06T11:00:00Z',
    Description: '$2.50 Domestic Drafts every Thursday.  Pair that with $2 sliders and Thursday Night Football and youve got a party.  Check out our website and Facebook Page for the weekly Specialty Slider of the Day only $3',
    Distance: '6.6',
    Free: 'true',
    HasTime: 'true',
    Id: 'f5d6d6e1c60445879b386b6d5170c0cb',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Thirsty Thursdays',
          revP: '0',
          url: 'http://www.Facebook.com/Kick N It Sports Bar' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.medium.png',
    Name: 'Thirsty Thursdays',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2724741',
    Picked: 'false',
    PopularityIndex: '7',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fb1a23e0-e2c7-4209-afb8-9bee03f066a9.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '377095',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '12', '14', '10252', '75' ] },
    Tickets: '',
    Venue: 'Kick N It Sports Bar',
    Zip: '84107',
    ct: 
     { email: 'kicknitatjuices@gmail.com',
       name: 'Justin Troyer',
       org: 'Kick N It Sports Grill',
       phone: '801-448-6230' },
    enhance: 'false',
    latitude: '40.665349066257477',
    lm: '2016-08-25T21:27:17.927Z',
    longitude: '-111.88825115561485' },
  { Address: '175 E. 200 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T11:00:00Z',
    Description: 'CUAC is pleased to present Discover Zaqistan: The Art of Adventure by the Zaqistan Tourism Board. The Republic of Zaqistan is located just west of the Great Salt Lake. Founded in 2005 by New York City-based artist Zaq Landsberg as a response to the political climate at the time, the project continues to be conceptually tied to current events. This year, Zaqistan is opening up its doors to tourism and partnering with *CUAC* to host expeditions into the desolate nation as well as an exhibition on the country.',
    Distance: '0.4',
    Free: 'true',
    HasTime: 'true',
    Id: '961704d0e11b466388a2c46e882f3bb7',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Discover Zaqistan: The Art of Adventure',
          revP: '0',
          url: 'http://cuartcenter.org' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.medium.png',
    Name: 'Discover Zaqistan: The Art of Adventure',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2759785',
    Picked: 'false',
    PopularityIndex: '7',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b2bb1fa6-ff15-43a3-8402-6bec78b69aa1.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '388158',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '32', '3', '5' ] },
    Tickets: '',
    Venue: 'CUAC',
    Zip: '84101',
    ct: 
     { email: 'art@cuartcenter.org',
       name: 'Nancy Rivera',
       org: 'CUAC',
       phone: '385-215-6768' },
    enhance: 'false',
    latitude: '40.7657470703125',
    lm: '2016-09-07T16:03:56.227Z',
    longitude: '-111.88483428955078' },
  { Address: '202 W. 300 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T12:00:00Z',
    Description: 'The annual Utah Humanities Book Festival is Utah’s oldest and only statewide book festival and has become Utah’s signature literary event.\r\n\r\nEach year, the festival is a chance for book lovers of all types to enjoy some great, free-of-charge literary events at locations throughout Utah.\r\n\r\nMany thanks to the Book Festival’s sponsors: the George S and Dolores Dore Eccles Foundation, the R. Harold Burton Foundation, Chevron, the Salt Lake City Public Library, Salt Lake County Zoo, Arts & Parks Fund, the Utah Office of Tourism, the National Endowment for the Humanities, the Charles Redd Center for Western Studies, The King’s English Bookshop, Weller Book Works, *Catalyst*, *SLUG Magazine*, *The Enterprise*, and *City Weekly*.',
    Distance: '1.1',
    Free: 'true',
    HasTime: 'true',
    Id: '54cabadd6a8b45e8b7e6dc54001eb438',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FestivalFair' },
    Links: 
     { jsLink: 
        { name: 'Utah Humanities Book Festival',
          revP: '0',
          url: 'http://www.utahhumanities.org/index.php/Center-for-the-Book/book-festival.html' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.medium.png',
    Name: 'Utah Humanities Book Festival',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2816927',
    Picked: 'false',
    PopularityIndex: '8',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/77e04e8b-9418-49f7-bccb-e849785e0e8c.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '407751',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '31', '453', '189', '4', '5' ] },
    Tickets: '',
    Venue: 'Utah Humanities',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.773826315999031',
    lm: '2016-09-28T04:52:43.856Z',
    longitude: '-111.89963042736053' },
  { Address: '280 W. 500 N.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T16:00:00Z',
    Description: 'Receive one-on-one collaborative writing assistance and helpful feedback in a supportive environment. Bring any type of writing: resumes, essays, short stories, or letters. Writing Coaching is open to all ages.\r\n\r\nIt\'s free, though schedule 30-minute session or submit work at the Community Writing Center\'s website, http://www.slcc.edu/cwc.',
    Distance: '1.4',
    Free: 'true',
    HasTime: 'true',
    Id: '542af89750b04d49a0d8ea357825859e',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'SLCC Community Writing Center Writing Coaching',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5831/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.medium.png',
    Name: 'SLCC Community Writing Center Writing Coaching',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785003',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/c567cb90-38eb-4d7a-95e2-e446e20d17b8.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '395623',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '27', '7', '4' ] },
    Tickets: '',
    Venue: 'Marmalade Library',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.775393396615982',
    lm: '2016-09-15T14:08:09.196Z',
    longitude: '-111.90541863441467' },
  { Address: '577 S. 900 West',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:00:00Z',
    DateStart: '2016-10-06T16:00:00Z',
    Description: 'My paintings come from my heart. It would be easy for me to edit out all that is meaningful in my paintings by judging an inspiration as too sentimental, too complicated, or just plain crazy. Wrestling with my inner voices, both angels and demons, I struggle to create a personal visual language.\r\n\r\nPainting affirms my love of the messy tactile world, the world of color and surfaces. The paint becomes my micro-universe where I play with textures, rhythms of line and patterns of form, and, more importantly, the duality of creation and destruction. I layer the paint and collage to create real depth on the pictorial surface. Primitive art inspires my work in its disregard for anatomical correctness and illusionary effects of perspective. An Egyptian frontal view of the shoulders, an Aboriginal dot, an Assyrian eye facing forward in a facial profile, and an Anasazi headdress can all be found in my work. Much inspiration comes from the work of Paul Klee, Picasso, and Chagall who were each inspired, like me, by primitive art.\r\n\r\nThe subjects of my work sometimes reflects experiences my life with my family and animals, but they can also be a reflection of the inner journeys of my mind. This messy humanness I share with all the people who have come before me and who will come after me fuels my artistic engine. Through deceptively simple images and rich layering of texture, I intend for my paintings to speak beyond culture, time, and location. Employing a personal symbolic language, my paintings are the vehicle in my search for wholeness and connection.',
    Distance: '1.2',
    Free: 'true',
    HasTime: 'true',
    Id: '3139bc3ca2484ceaa735d8392d68ddc1',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'ArtExhibit' },
    Links: 
     { jsLink: 
        { name: 'Willamarie Huelskamp: A Peaceful Place',
          revP: '0',
          url: 'http://www.slcpl.lib.ut.us/events/view/5615/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.medium.png',
    Name: 'Willamarie Huelskamp: A Peaceful Place',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2615308',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3d258688-b4f9-4c16-8193-55d4201b4b57.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '402507',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '3', '10170', '5' ] },
    Tickets: '',
    Venue: 'Salt Lake City Chapman Library',
    Zip: '84101',
    ct: 
     { email: { '$': { 'i:nil': 'true' } },
       name: { '$': { 'i:nil': 'true' } },
       org: { '$': { 'i:nil': 'true' } },
       phone: '(801) 594-8623, (801) 524-8200' },
    enhance: 'false',
    latitude: '40.749713256955147',
    lm: '2016-09-21T22:22:42.295Z',
    longitude: '-111.90740682184696' },
  { Address: '1575 W. 1000 North',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T17:30:00Z',
    DateStart: '2016-10-06T16:30:00Z',
    Description: 'Hang out with other neighborhood teens in a space created for you! The Teen Zone is a space made just for teens ages 12–18 that is open every Monday, Thursday, and Friday. Teens can participate in a designated activity that the Teen Zone is hosting, or can use the space to hang out, chat with friends, lounge on some comfy chairs, noodle on a ukulele, or curl up with a book.',
    Distance: '3.3',
    Free: 'true',
    HasTime: 'true',
    Id: '3cdf07146b0643aa85c18accda599a88',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: 
     { jsLink: 
        { name: 'Teen Zone',
          revP: '0',
          url: 'http://www.slcpl.org/events/view/5689/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.medium.png',
    Name: 'Teen Zone',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785200',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/b81fca70-ced7-4dcc-b94f-e7069ce73ac7.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '395686',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '81', '10255', '358', '35', '5', '15', '53', '76' ] },
    Tickets: '',
    Venue: 'Day-Riverside Branch',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.790485382080078',
    lm: '2016-09-15T14:08:15.553Z',
    longitude: '-111.93634796142578' },
  { Address: '1375 S. Concord St.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T18:00:00Z',
    DateStart: '2016-10-06T16:30:00Z',
    Description: 'Flex your creativity and learn a variety of new crafts. Each week, teens can take part in creative workshops with supplies provided by the Library. *No registration is required.*',
    Distance: '2.5',
    Free: 'true',
    HasTime: 'true',
    Id: '61014bb3cb504c4d8d1fc57f2cde20e9',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'SpecialEvent' },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.medium.png',
    Name: 'Teen DIY',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2771880',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fd60c49f-78f7-4fdd-953d-ebe748cafebe.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '391680',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '51', '81', '10255', '35', '5', '15', '76' ] },
    Tickets: '',
    Venue: 'Salt Lake City Glendale Library',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.738994598388672',
    lm: '2016-09-19T23:11:23.333Z',
    longitude: '-111.92671966552734' },
  { Address: '2750 N. University Park Blvd.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Layton, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T17:30:00Z',
    Description: '18th Annual WSU Diversity Conference\r\n\r\n“Privileged History: Where Did All the Diversity Go?” with Dr\\. James W\\. Loewen, author of “Lies My Teacher Told Me”\r\n\r\nOpening Session at WSU Davis:\r\n"Precious Knowledge" Film and Discussion\r\nOctober 6, 2016\r\n5:30 \\- 8 p\\.m\\.\r\nBuilding 3 Ballrooms',
    Distance: '21.5',
    Free: 'true',
    HasTime: 'true',
    Id: 'e973df57f52b43f4b51919441b52583a',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: '18th Annual WSU Diversity Conference',
          revP: '0',
          url: 'http://www.weber.edu/diversity/wsu-diversity-conference.html' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.medium.png',
    Name: '18th Annual WSU Diversity Conference',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2767379',
    Picked: 'false',
    PopularityIndex: '6',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/467aae5e-eb0e-4f9d-9221-8f3497fac7c4.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '7', '39' ] },
    Tickets: '',
    Venue: 'Weber State University Davis Campus',
    Zip: '84041',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '41.0659294128418',
    lm: '2016-09-09T00:36:18.455Z',
    longitude: '-111.96102142333984' },
  { Address: '450 W. Center St.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Provo, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T19:00:00Z',
    DateStart: '2016-10-06T17:30:00Z',
    Description: 'Come hear local author David Pace read from his debut novel, *Dream House on Golan Drive!*\r\n\r\nIt is the year 1972, and Riley Hartley finds that he, his family, community, and his faith are entirely indistinguishable from each other. He is eleven. A young woman named Lucy claims God has revealed to her that she is to live with Riley’s family. Her quirks are strangely disarming, her relentless questioning of their lives incendiary and sometimes comical. Her way of taking religious practice to its logical conclusion leaves a strong impact on her hosts and propels Riley outside his observable universe and toward a trajectory of self-discovery.\r\n\r\n___\r\n Set in Provo and New York City during the seventies and eighties, the story encapsulates the normal expectations of a Mormon experience and turns them on their head. The style, too, is innovative in how it employs “Zed,” one of the apocryphal Three Nephites who with another immortal figure, the Wandering Jew of post-biblical legend, engage regularly in light-hearted banter and running commentary, animating the story and leavening the heartache with humor and tenderness.',
    Distance: '38.2',
    Free: 'true',
    HasTime: 'true',
    Id: '9ca9ec7890034cdb9d34f87f71da9076',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'Author' },
    Links: 
     { jsLink: 
        { name: 'David Pace: Dream House on Golan Drive',
          revP: '0',
          url: 'http://pioneerbook.com/' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.medium.png',
    Name: 'David Pace: Dream House on Golan Drive',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2808563',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4ee7c93f-92b0-469e-bc48-a546029b9bc8.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '401680',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '4', '189' ] },
    Tickets: '',
    Venue: 'Pioneer Book',
    Zip: '84606',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.234066009521484',
    lm: '2016-09-21T18:20:55.32Z',
    longitude: '-111.66659545898437' },
  { Address: '2131 S 1100 E',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T19:00:00Z',
    DateStart: '2016-10-06T17:30:00Z',
    Description: 'Join us for a U Drive Electric Workshop on Thursday, October 6th at the Sprague Library Meeting Room. The U Drive Electric Team will be on hand to tell you more about the benefits of driving electric, and how U Drive Electric can help you make the switch to an EV. The participating dealerships will also have EVs on display before and after the workshop. Presentations to be followed by Q&A. Please RSVP.',
    Distance: '2.8',
    Free: 'true',
    HasTime: 'true',
    Id: 'f8430792bce343aa820b028ae894d7e3',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'U Drive Electric Workshop',
          revP: '0',
          url: 'http://utahev.org/events/3-u-drive-electric-workshop-sprague-library-meeting-room' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.medium.png',
    Name: 'U Drive Electric Workshop',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2840068',
    Picked: 'false',
    PopularityIndex: '5',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ef64f1d7-78d8-4ada-9892-8c3eeb668f5e.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '410074',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '39', '10120', '7', '11' ] },
    Tickets: 
     { jsLink: 
        { name: 'U Drive Electric Workshop',
          revP: '0',
          url: 'http://utahev.org/events/3-u-drive-electric-workshop-sprague-library-meeting-room' } },
    Venue: 'Sprague Library Meeting Room',
    Zip: '84101',
    ct: 
     { email: 'liamharry0506@gmail.com',
       name: 'Liam Harry',
       org: 'Utah Clean Energy',
       phone: { '$': { 'i:nil': 'true' } } },
    enhance: 'false',
    latitude: '40.725295096635818',
    lm: '2016-09-29T23:17:21.308Z',
    longitude: '-111.85957096517086' },
  { Address: '210 E. 400 S.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T20:00:00Z',
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Social media (like Facebook and Twitter, to name a couple) is one of the most common means to spread ideas and information in our world. While social media offers great tools for exchanging ideas and opinions, it can also create conflict and problems. In this workshop, you will learn how to best structure your social media posts to engage and persuade in a positive and productive way. Bring an internet capable device or use one of ours so we can create posts during the workshop.\r\n\r\n**Cost: Free. No registration is required.**',
    Distance: '0.2',
    Free: 'true',
    HasTime: 'true',
    Id: '9638a939aaa04ca3b80f31785d7f120c',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Writing for Change: Social Media',
          revP: '0',
          url: 'http://www.slcc.edu/cwc/index.aspx' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.medium.png',
    Name: 'Writing for Change: Social Media',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2785984',
    Picked: 'false',
    PopularityIndex: '4',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: 'Free',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/3f638d7f-a62d-42a4-804b-7783df126bb5.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '396082',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '27', '39', '41', '4', '7' ] },
    Tickets: '',
    Venue: 'Salt Lake Community College Community Writing Center',
    Zip: '84101',
    ct: 
     { email: 'cwc@slcc.edu',
       name: 'Nic Contreras',
       org: 'SLCC Community Writing Center',
       phone: '(801)674-2036' },
    enhance: 'false',
    latitude: '40.759559631347656',
    lm: '2016-09-15T04:38:34.696Z',
    longitude: '-111.88392639160156' },
  { Address: '536 W. 100 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Metalcore band Beartooth is bringing their tour in support of their latest album, *Aggressive*, to The Complex October 6th. Come rock out!',
    Distance: '1.1',
    Free: 'false',
    HasTime: 'true',
    Id: '1ba837e3d9ce417dbfdaafd577818be0',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.medium.png',
    Name: 'Beartooth',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2589630',
    Picked: 'false',
    PopularityIndex: '7',
    Price: '19.50',
    PriceHigh: '25',
    PriceText: '$19.50 Adv/$25 Day Of',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d0092ffb-d5f7-49ce-8bae-138d402d4a14.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '404240',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '17', '2' ] },
    Tickets: 
     { jsLink: 
        { name: 'Beartooth',
          revP: '0',
          url: 'http://smithstix.com/music/event/18926/beartooth-oct-6' } },
    Venue: 'The Complex',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.767715454101563',
    lm: '2016-09-23T17:39:23.387Z',
    longitude: '-111.90690612792969' },
  { Address: '49 S Main St',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Spanish Fork, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Come join Austin Brunson, Family Life Educator, from USU to learn how to follow your heart without losing your mind\\. You can sign up for classes at www\\.eventbrite\\.com, or at healthyrelationshipsutah\\.org\\.',
    Distance: '46.6',
    Free: 'true',
    HasTime: 'true',
    Id: '371c1aba5d1240a78618b16767f05581',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'ServeDaily',
          revP: '0',
          url: 'http://Join Family Life Educator Austin Brunson for healthy relationship tips' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.medium.png',
    Name: 'Are You Over 18 and are Single or Dating?',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2814292',
    Picked: 'false',
    PopularityIndex: '9',
    Price: '0',
    PriceHigh: '0',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/d75646ff-e15e-493d-82ad-c48c4f3c3506.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '10', '64', '7', '41' ] },
    Tickets: '',
    Venue: 'Spanish Fork Library',
    Zip: '84660',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.1091615111',
    lm: '2016-09-26T13:51:06.99Z',
    longitude: '-111.6547306627' },
  { Address: '132 South 800 West',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T19:00:00Z',
    DateStart: '2016-10-06T18:00:00Z',
    Description: 'Learn to dance flamenco with complementos (props). We will focus on technique with shawls, fans, castanets, and MORE! This class is for all levels. Drop in anytime. $10/class',
    Distance: '0.7',
    Free: 'false',
    HasTime: 'true',
    Id: '31391d70f2c9482fb5b83eb19b59e491',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ffeca690-f5f0-4662-b1df-850319247aba.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'Dance' },
    Links: 
     { jsLink: 
        { name: 'Flamenco Dance with Props',
          revP: '0',
          url: 'https://www.facebook.com/flamencodellago/?ref=aymt_homepage_panel' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ffeca690-f5f0-4662-b1df-850319247aba.medium.png',
    Name: 'Flamenco Dance with Props',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2549967',
    Picked: 'false',
    PopularityIndex: '6',
    Price: '10',
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: '$10/class or $35/month',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/ffeca690-f5f0-4662-b1df-850319247aba.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '409135',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '18', '225', '93', '17', '2' ] },
    Tickets: '',
    Venue: 'Sugar Space',
    Zip: '84101',
    ct: 
     { email: 'katie@flamencodellago.com',
       name: 'Katie Sheen Abbott',
       org: 'Flamenco del Lago',
       phone: '801-879-6167' },
    enhance: 'false',
    latitude: '40.751995146274567',
    lm: '2016-09-28T19:31:40.569Z',
    longitude: '-111.89481988549232' },
  { Address: '1901 E. South Campus Dr.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: '2016-10-06T20:30:00Z',
    DateStart: '2016-10-06T18:30:00Z',
    Description: 'Anyone can learn to draw! This class will encourage you to explore drawing through a variety of materials, methods, and philosophies. You will become familiar with charcoal, ink, graphite, oil pastels, and even alternative drawing materials as you complete exercises and activities to help you see what is in front of you and set your vision down on paper. Gain confidence as you become acquainted with your own unique drawing style. Please bring a smock or wear "art clothes," and bring a large (6x10x4 inch) container for take-home supplies. Special fee covers all materials.',
    Distance: '2.7',
    Free: 'false',
    HasTime: 'true',
    Id: 'c208fbb9c55b4d219e4977d09a34405a',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/be1f6609-bc81-4308-b96e-f2ea535df4ec.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Beginning Drawing (LLART 68)',
          revP: '0',
          url: 'https://continue.utah.edu/lifelong/class/llart_68_beginning_drawing#sthash.TneBOdiP.dpuf' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/be1f6609-bc81-4308-b96e-f2ea535df4ec.medium.png',
    Name: 'Beginning Drawing (LLART 68)',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2666514',
    Picked: 'false',
    PopularityIndex: '6',
    Price: '159.00',
    PriceHigh: '159.00',
    PriceText: 'Tuition: $139.00 + Special Fee: $20.00 = $159.00',
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/be1f6609-bc81-4308-b96e-f2ea535df4ec.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '363304',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '41', '7' ] },
    Tickets: 
     { jsLink: 
        { name: 'Beginning Drawing (LLART 68)',
          revP: '0',
          url: 'https://continue.utah.edu/lifelong/class/llart_68_beginning_drawing#sthash.TneBOdiP.dpuf' } },
    Venue: 'Annex Building',
    Zip: '84101',
    ct: 
     { email: 'jonathan.harman@utah.edu',
       name: 'Jonathan Harman',
       org: 'University of Utah Continuing Education and Community Engagement / Lifelong Learning',
       phone: '801-585-5184' },
    enhance: 'false',
    latitude: '40.761964246630669',
    lm: '2016-08-09T16:50:37.419Z',
    longitude: '-111.83657504618168' },
  { Address: '741 Kilby Court',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T19:00:00Z',
    Description: 'SLC Pink is a submission based multi\\-media zine series for female, trans, and non\\-binary artists\\. \r\nEdition two, "Self Portrait", will be released at Kilby Court on October 6th\\.\r\nLine\\-up will be annouced soon\\! Stay tuned\\! \r\nTickets: $10',
    Distance: '0.8',
    Free: 'false',
    HasTime: 'true',
    Id: 'e561bc00727148968942efb5b5fc26d1',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7d02ae8d-4cc4-49f0-9b51-70fad1482774.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: 
     { jsLink: 
        { name: 'Kilby Court',
          revP: '0',
          url: 'http://www.facebook.com/events/285848491783451' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7d02ae8d-4cc4-49f0-9b51-70fad1482774.medium.png',
    Name: 'SLC PINK Edition 2 Release Party!',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2660445',
    Picked: 'false',
    PopularityIndex: '9',
    Price: '10',
    PriceHigh: '10',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7d02ae8d-4cc4-49f0-9b51-70fad1482774.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '2', '17', '100', '5', '381' ] },
    Tickets: 
     { jsLink: 
        { name: 'TicketFly',
          revP: '100',
          url: 'http://www.shareasale.com/r.cfm?u=867088&b=234786&m=27601&urllink=https%3a%2f%2fwww.ticketfly.com%2fpurchase%2fevent%2f1278341%2ftfly%3futm_medium%3dapi' } },
    Venue: 'Kilby Court',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7535897195',
    lm: '2016-08-05T14:30:55.956Z',
    longitude: '-111.9007536024' },
  { Address: { '$': { 'i:nil': 'true' } },
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Stansbury Park, UT',
    Date: '2016-10-06T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-06T19:00:00Z',
    Description: 'Join us for an amazing and intimate evening with Willy Porter and Carmen Nickerson\\! \r\n\r\nSearching for the shaman that lives inside the guitar has led Willy Porter on a musical and personal odyssey spanning over two decades, 10 albums, and multiple continents\\. \r\n\r\nHis live shows are guitar driven events\\- equal parts grit, soul, and muscle \\-that are electrifying, dynamic, and wholly original in the way that Porter’s voice blends and fuses with his virtuoso fret work\\. Add in the fantastic vocal \\(and light percussion\\) talents of Carmen Nickerson and what you have is an evening that won\'t soon be forgotten\\!',
    Distance: '22.9',
    Free: 'false',
    HasTime: 'true',
    Id: '34a92d1f47514c308c4f6c71d011e3a8',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fe3fc004-2e40-45d8-9dd6-5ffb49eee2f3.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fe3fc004-2e40-45d8-9dd6-5ffb49eee2f3.medium.png',
    Name: 'Willy Porter and Carmen Nickerson at the Stansbury Concert Series',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2704504',
    Picked: 'false',
    PopularityIndex: '10',
    Price: '0',
    PriceHigh: '30',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/fe3fc004-2e40-45d8-9dd6-5ffb49eee2f3.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '2', '102', '17', '94' ] },
    Tickets: 
     { jsLink: 
        { name: 'Willy Porter and Carmen Nickerson at the Stansbury Concert Series',
          revP: '0',
          url: 'https://squareup.com/store/stansbury-concert-series' } },
    Venue: 'The Coulter House',
    Zip: { '$': { 'i:nil': 'true' } },
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.637859344482422',
    lm: '2016-08-19T12:39:17.464Z',
    longitude: '-112.29521942138672' } ]