[ { Address: '1465 Stringtown Road',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Midway, UT',
    Date: '2016-10-01T00:00:00Z',
    DateEnd: '2016-10-01T13:00:00Z',
    DateStart: '2016-10-01T07:30:00Z',
    Description: 'Test your mettle in a race with thunder. Reserved for a brave few, it\'s 12 kilometers of willpower vs horsepower. From the Dam to the Station, along the scenic route of the Heber Valley Railroad, you will write the next chapter in the iconic story of Man and Machine.\r\n\r\n___\r\nWill you make it back to the platform before the Mighty Train? There\'s only one way to find out.',
    Distance: '28.5',
    Free: 'false',
    HasTime: 'true',
    Id: 'ff4b16823b7d435cbf2797fa42ea53bd',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4f8e0bc0-d96a-45df-9df8-751802b8a595.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4f8e0bc0-d96a-45df-9df8-751802b8a595.medium.png',
    Name: 'The Dam Train Race',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2770890',
    Picked: 'false',
    PopularityIndex: '13',
    Price: '30',
    PriceHigh: '50',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/4f8e0bc0-d96a-45df-9df8-751802b8a595.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '391001',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '167', '10048', '38', '6' ] },
    Tickets: 
     { jsLink: 
        { name: 'The Dam Train Race',
          revP: '0',
          url: 'http://thedamtrainrace.com/' } },
    Venue: 'Heber Valley Historic Railroad',
    Zip: '84049',
    ct: 
     { email: 'support@thedamtrainrace.com',
       name: { '$': { 'i:nil': 'true' } },
       org: { '$': { 'i:nil': 'true' } },
       phone: { '$': { 'i:nil': 'true' } } },
    enhance: 'false',
    latitude: '40.4874382019043',
    lm: '2016-09-09T20:24:27.133Z',
    longitude: '-111.48143005371094' },
  { Address: '300 W. 300 South',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-01T00:00:00Z',
    DateEnd: '2016-10-01T14:00:00Z',
    DateStart: '2016-10-01T08:00:00Z',
    Description: 'From its inception in 1992, the Downtown Farmers Market has become a summer tradition for Salt Lake City residents and visitors. Located in historic Pioneer Park, the Saturday Farmers Market has infused vitality into the middle ground between East Bench and West Side neighborhoods.',
    Distance: '0.6',
    Free: 'true',
    HasTime: 'true',
    Id: 'ca8b578d6a7f4ab099b23a0c64966596',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7a5fa526-ae1c-4de0-925d-879520be27e9.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FarmersMarket' },
    Links: 
     { jsLink: 
        { name: 'Downtown Farmers Market',
          revP: '0',
          url: 'http://www.slcfarmersmarket.org/markets/saturday-farmers-market' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7a5fa526-ae1c-4de0-925d-879520be27e9.medium.png',
    Name: 'Downtown Farmers Market',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2178423',
    Picked: 'false',
    PopularityIndex: '14',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7a5fa526-ae1c-4de0-925d-879520be27e9.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '317473',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '76', '385', '54' ] },
    Tickets: '',
    Venue: 'Pioneer Park',
    Zip: '84101',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.762642845511436',
    lm: '2016-06-08T17:40:45.264Z',
    longitude: '-111.8997598439455' },
  { Address: '201 Presidents Cir',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Salt Lake City, UT',
    Date: '2016-10-01T00:00:00Z',
    DateEnd: { '$': { 'i:nil': 'true' } },
    DateStart: '2016-10-01T09:00:00Z',
    Description: 'Registration for creative dance, satellite, ballet, hip hop, and Dancers with Disabilities classes for the the 2016-2017 school year is now available.It should be an amazing year of dance.',
    Distance: '2',
    Free: 'false',
    HasTime: 'true',
    Id: '990ed447eee047aba6624879be8758d9',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.large.png' } },
    IsPromotion: 'false',
    Labels: { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' } },
    Links: '',
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.medium.png',
    Name: 'Tanner Dance Classes',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2628342',
    Picked: 'false',
    PopularityIndex: '10',
    Price: '100',
    PriceHigh: '750',
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/7ed541cf-791e-4cf0-9729-b4d08c053230.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: { '$': { 'i:nil': 'true' } },
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '2', '17', '18' ] },
    Tickets: 
     { jsLink: 
        { name: 'Tanner Dance Classes',
          revP: '0',
          url: 'http://www.tannerdance.utah.edu/' } },
    Venue: 'The University of Utah',
    Zip: '84112',
    ct: { '$': { 'i:nil': 'true' } },
    enhance: 'false',
    latitude: '40.7655087858',
    lm: '2016-07-31T17:09:19.314Z',
    longitude: '-111.8498969078' },
  { Address: '151 S. 1100 W.',
    AllDay: 'false',
    BiasTags: 
     { '$': 
        { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays',
          'i:nil': 'true' } },
    CityState: 'Farmington, UT',
    Date: '2016-10-01T00:00:00Z',
    DateEnd: '2016-10-01T14:00:00Z',
    DateStart: '2016-10-01T09:00:00Z',
    Description: 'DogFest Walk \'N Roll **Grab a Leash! **Join the fun at this accessible, family- and dog-friendly walk and festival, benefiting Canine Companions for Independence and the mission of providing highly trained assistance dogs to people with disabilities free of charge.\r\n\r\nRegister for free\r\n\r\nForm a team\r\n\r\nCollect donations\r\n\r\nWalk \'n roll\r\n\r\nChange a life',
    Distance: '15.2',
    Free: 'true',
    HasTime: 'true',
    Id: '4a6fe0b93c564b1489b966e2c516cd48',
    Images: 
     { jsImg: 
        { id: '1',
          url: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a51111ad-4b06-4c54-8877-c442aa46f74c.large.png' } },
    IsPromotion: 'false',
    Labels: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       string: 'FestivalFair' },
    Links: 
     { jsLink: 
        { name: 'DogFest Walk \'N Roll',
          revP: '0',
          url: 'http://cci.org/DogFestWasatch' } },
    Media: { '$': { 'i:nil': 'true' } },
    MediumImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a51111ad-4b06-4c54-8877-c442aa46f74c.medium.png',
    Name: 'DogFest Walk \'N Roll',
    Occurances: { '$': { 'i:nil': 'true' } },
    PId: '2709068',
    Picked: 'false',
    PopularityIndex: '38',
    Price: { '$': { 'i:nil': 'true' } },
    PriceHigh: { '$': { 'i:nil': 'true' } },
    PriceText: { '$': { 'i:nil': 'true' } },
    SmallImg: 'https://citysparkstorage.blob.core.windows.net/portalimages/portalimages/a51111ad-4b06-4c54-8877-c442aa46f74c.small.png',
    Sponsor: { '$': { 'i:nil': 'true' } },
    SubmitPID: '374344',
    Tags: 
     { '$': { 'xmlns:d4p1': 'http://schemas.microsoft.com/2003/10/Serialization/Arrays' },
       int: [ '69', '67', '31', '5', '10', '11' ] },
    Tickets: 
     { jsLink: 
        { name: 'DogFest Walk \'N Roll',
          revP: '0',
          url: 'http://cci.org/DogFestWasatch' } },
    Venue: 'Legacy Events Center',
    Zip: '84025',
    ct: 
     { email: 'chpalmer68@yahoo.com',
       name: 'Charlene Palmer, Volunteer',
       org: 'Canine Companions for Independence',
       phone: '801-597-4419' },
    enhance: 'false',
    latitude: '40.979645624756813',
    lm: '2016-08-22T14:57:54.562Z',
    longitude: '-111.91128596663475' } ]